name: nginx & docker compose config file

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{  secrets.SSH_HOST }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            whoami
            cd /critik-v
            rm -rf ./${{github.event.repository.name}}
            git clone https://github.com/${{github.repository}}.git
            cd ./${{github.event.repository.name}}
            cp nginx.conf /etc/nginx/nginx.conf
            cp docker-compose.yml /critik-v/docker-compose.yml
            sudo systemctl restart nginx
